"""Adicionando a opção de tipo de categoria neutra

Revision ID: 04c54eba65d8
Revises: e51894fb4870
Create Date: 2026-01-13 13:09:44.844368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c54eba65d8'
down_revision: Union[str, Sequence[str], None] = 'e51894fb4870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
