"""refactor_merchant_categories_and_fix_uniqueness

Revision ID: 0970ee4ca956
Revises: 5d9d4215e9d6
Create Date: 2026-02-04 11:20:02.502198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0970ee4ca956'
down_revision: Union[str, Sequence[str], None] = '5d9d4215e9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_merchants_income_category'), 'merchants', type_='foreignkey')
    op.drop_constraint(op.f('fk_merchants_expense_category'), 'merchants', type_='foreignkey')
    op.drop_column('merchants', 'expense_category_id')
    op.drop_column('merchants', 'income_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('income_category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('expense_category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_merchants_expense_category'), 'merchants', 'categories', ['expense_category_id'], ['id'])
    op.create_foreign_key(op.f('fk_merchants_income_category'), 'merchants', 'categories', ['income_category_id'], ['id'])
    # ### end Alembic commands ###
