"""o nome do merchant é único apenas por usuário

Revision ID: 0c1b21122f37
Revises: 0970ee4ca956
Create Date: 2026-02-04 11:25:59.514331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1b21122f37'
down_revision: Union[str, Sequence[str], None] = '0970ee4ca956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('merchants_name_key'), 'merchants', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('merchants_name_key'), 'merchants', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
