"""Add merchant normalization system

Revision ID: 13710dd1d76d
Revises: 7f92a9c37867
Create Date: 2025-12-30 22:32:00.408548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13710dd1d76d"
down_revision: Union[str, Sequence[str], None] = "7f92a9c37867"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Primeiro, remover a foreign key e as colunas que referenciam 'aliases'
    op.drop_constraint(op.f("payments_alias_id_fkey"), "payments", type_="foreignkey")
    op.drop_column("payments", "alias")
    op.drop_column("payments", "alias_id")

    # Agora podemos dropar a tabela aliases sem problemas
    op.drop_table("aliases")

    # Adicionar novas colunas e relacionamentos
    op.add_column("payments", sa.Column("merchant_id", sa.UUID(), nullable=True))
    op.add_column("payments", sa.Column("bank_id", sa.UUID(), nullable=False))
    op.alter_column(
        "payments",
        "date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "payments", "banks", ["bank_id"], ["id"])
    op.create_foreign_key(None, "payments", "merchants", ["merchant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("alias_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "payments", sa.Column("alias", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.create_foreign_key(
        op.f("payments_alias_id_fkey"), "payments", "aliases", ["alias_id"], ["id"]
    )
    op.alter_column(
        "payments",
        "date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("payments", "bank_id")
    op.drop_column("payments", "merchant_id")
    op.create_table(
        "aliases",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("bank_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["banks.id"], name=op.f("aliases_bank_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("aliases_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("aliases_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
