"""add_server_defaults_to_open_finance_items

Revision ID: 184d41fe51e1
Revises: 0c1b21122f37
Create Date: 2026-02-04 12:14:38.958714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184d41fe51e1'
down_revision: Union[str, Sequence[str], None] = '0c1b21122f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
