"""criando a tabela de user_category_settings

Revision ID: 1ad1f7ebbe02
Revises: 5925182a2bbd
Create Date: 2026-01-09 15:57:34.284373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad1f7ebbe02'
down_revision: Union[str, Sequence[str], None] = '5925182a2bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payments_category_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_category_id_fkey'), 'payments', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
