"""Adicionando a opção de descrição para o pagamento

Revision ID: 1dde0e3f8c2c
Revises: e6e441fd4e4a
Create Date: 2026-01-06 11:10:55.548603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dde0e3f8c2c'
down_revision: Union[str, Sequence[str], None] = 'e6e441fd4e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('payments', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'description')
    op.alter_column('merchants', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
