"""Adicionando o campo de slug e cor hexadecimal para a tabela de categoria

Revision ID: 38cbdc721974
Revises: 1dde0e3f8c2c
Create Date: 2026-01-07 22:45:35.148207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38cbdc721974"
down_revision: Union[str, Sequence[str], None] = "1dde0e3f8c2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column("categories", sa.Column("slug", sa.String(), nullable=True))
    op.add_column("categories", sa.Column("color_hex", sa.String(), nullable=True))

    # 2. Update existing rows
    # We'll use a generic update for simplicity, or complex logic if needed.
    # For now, let's just set a default to avoid crashes.
    op.execute(
        "UPDATE categories SET slug = lower(replace(name, ' ', '-')), color_hex = '#000000' WHERE slug IS NULL"
    )

    # 3. Alter columns to be non-nullable
    op.alter_column("categories", "slug", nullable=False)
    op.alter_column("categories", "color_hex", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "color_hex")
    op.drop_column("categories", "slug")
    # ### end Alembic commands ###
