"""add_profile_image_url_to_user

Revision ID: 486074e95f0c
Revises: 9e754df95b08
Create Date: 2026-02-17 21:05:13.124063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "486074e95f0c"
down_revision: Union[str, Sequence[str], None] = "9e754df95b08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("profile_image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_image_url")
    # ### end Alembic commands ###
