"""add category type

Revision ID: 504f35b44f38
Revises: 1ad1f7ebbe02
Create Date: 2026-01-09 19:01:29.694922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "504f35b44f38"
down_revision: Union[str, Sequence[str], None] = "1ad1f7ebbe02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create Enum Type explicitly
    category_type = sa.Enum("INCOME", "EXPENSE", name="categorytype")
    category_type.create(op.get_bind(), checkfirst=True)

    # 2. Add columns as nullable first
    op.add_column("categories", sa.Column("slug", sa.String(), nullable=True))
    op.add_column("categories", sa.Column("type", category_type, nullable=True))

    # 3. Data Migration (Backfill)
    # Default slug to lower(name)
    op.execute("UPDATE categories SET slug = lower(name)")
    # Default type to 'EXPENSE'
    op.execute("UPDATE categories SET type = 'EXPENSE'")

    # 4. Enforce Non-Null
    op.alter_column("categories", "slug", nullable=False)
    op.alter_column("categories", "type", nullable=False)

    op.create_unique_constraint(None, "categories", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="unique")
    op.drop_column("categories", "type")
    op.drop_column("categories", "slug")

    # Drop Enum type
    sa.Enum(name="categorytype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
