"""Remoção dos slugs da categoria novamente

Revision ID: 5925182a2bbd
Revises: 38cbdc721974
Create Date: 2026-01-08 16:38:47.154803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5925182a2bbd'
down_revision: Union[str, Sequence[str], None] = '38cbdc721974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
