"""add_unique_constraint_merchant_alias

Revision ID: 5a9a5a4594b8
Revises: 0b09e7de7ead
Create Date: 2026-02-14 12:39:03.822810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9a5a4594b8'
down_revision: Union[str, Sequence[str], None] = '0b09e7de7ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_merchant_alias_user_pattern', 'merchant_aliases', ['user_id', 'pattern'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_merchant_alias_user_pattern', 'merchant_aliases', type_='unique')
    # ### end Alembic commands ###
