"""remover campo slug da categoria

Revision ID: 84c8510c110d
Revises: 94c7d476d503
Create Date: 2025-12-31 00:05:22.288788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c8510c110d'
down_revision: Union[str, Sequence[str], None] = '94c7d476d503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
