"""Adicionando indices na tabela de pagamento

Revision ID: 94a7b575b097
Revises: 504f35b44f38
Create Date: 2026-01-12 14:59:34.166340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a7b575b097'
down_revision: Union[str, Sequence[str], None] = '504f35b44f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'merchants', ['name'])
    op.create_index(op.f('ix_payments_bank_id'), 'payments', ['bank_id'], unique=False)
    op.create_index(op.f('ix_payments_date'), 'payments', ['date'], unique=False)
    op.create_index(op.f('ix_payments_title'), 'payments', ['title'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_title'), table_name='payments')
    op.drop_index(op.f('ix_payments_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_bank_id'), table_name='payments')
    op.drop_constraint(None, 'merchants', type_='unique')
    # ### end Alembic commands ###
