"""alterando campo 'date' da tabela de pagamentos de datetime para date

Revision ID: 94c7d476d503
Revises: a9fafca2fc20
Create Date: 2025-12-30 23:34:54.864192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c7d476d503'
down_revision: Union[str, Sequence[str], None] = 'a9fafca2fc20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
