"""create_open_finance_accounts

Revision ID: 95a97440f1e6
Revises: ecb426da0bc9
Create Date: 2026-01-20 21:40:07.665916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95a97440f1e6'
down_revision: Union[str, Sequence[str], None] = 'ecb426da0bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_open_finance_items_pluggy_item_id'), table_name='open_finance_items')
    op.drop_index(op.f('ix_open_finance_items_user_id'), table_name='open_finance_items')
    op.drop_table('open_finance_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_finance_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pluggy_item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('UPDATED', 'UPDATING', 'LOGIN_ERROR', 'OUTDATED', 'WAITING_USER_INPUT', name='itemstatus'), autoincrement=False, nullable=False),
    sa.Column('bank_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('open_finance_items_bank_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('open_finance_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('open_finance_items_pkey'))
    )
    op.create_index(op.f('ix_open_finance_items_user_id'), 'open_finance_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_open_finance_items_pluggy_item_id'), 'open_finance_items', ['pluggy_item_id'], unique=True)
    # ### end Alembic commands ###
