"""Add merchant alias system with 1:N relationship

Revision ID: 98218dadb087
Revises: 13710dd1d76d
Create Date: 2025-12-30 22:59:16.492701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98218dadb087'
down_revision: Union[str, Sequence[str], None] = '13710dd1d76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_aliases', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('merchant_aliases', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('merchant_aliases_pattern_key'), 'merchant_aliases', type_='unique')
    op.drop_constraint(op.f('merchant_aliases_merchant_id_fkey'), 'merchant_aliases', type_='foreignkey')
    op.create_foreign_key(None, 'merchant_aliases', 'users', ['user_id'], ['id'])
    op.drop_column('merchant_aliases', 'pattern')
    op.drop_column('merchant_aliases', 'merchant_id')
    op.add_column('merchants', sa.Column('merchant_alias_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'merchants', 'merchant_aliases', ['merchant_alias_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.drop_column('merchants', 'merchant_alias_id')
    op.add_column('merchant_aliases', sa.Column('merchant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('merchant_aliases', sa.Column('pattern', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'merchant_aliases', type_='foreignkey')
    op.create_foreign_key(op.f('merchant_aliases_merchant_id_fkey'), 'merchant_aliases', 'merchants', ['merchant_id'], ['id'])
    op.create_unique_constraint(op.f('merchant_aliases_pattern_key'), 'merchant_aliases', ['pattern'], postgresql_nulls_not_distinct=False)
    op.drop_column('merchant_aliases', 'name')
    op.drop_column('merchant_aliases', 'user_id')
    # ### end Alembic commands ###
