"""add_flags_to_user_category_settings

Revision ID: 9e754df95b08
Revises: b879a29083f7
Create Date: 2026-02-16 14:35:00.929304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e754df95b08'
down_revision: Union[str, Sequence[str], None] = 'b879a29083f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_category_settings', sa.Column('is_investment', sa.Boolean(), nullable=True))
    op.add_column('user_category_settings', sa.Column('ignored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_category_settings', 'ignored')
    op.drop_column('user_category_settings', 'is_investment')
    # ### end Alembic commands ###
