"""Adicionando campo de slug na categoria para um nome mais padronizado

Revision ID: a9fafca2fc20
Revises: 98218dadb087
Create Date: 2025-12-30 23:26:18.889279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9fafca2fc20"
down_revision: Union[str, Sequence[str], None] = "98218dadb087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar coluna slug como nullable primeiro
    op.add_column("categories", sa.Column("slug", sa.String(), nullable=True))

    # Popular slug com base no nome (para registros existentes)
    op.execute("UPDATE categories SET slug = LOWER(REPLACE(name, ' ', '-'))")

    # Agora tornar NOT NULL
    op.alter_column("categories", "slug", nullable=False)

    # Adicionar constraint unique
    op.create_unique_constraint(None, "categories", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="unique")
    op.drop_column("categories", "slug")
    # ### end Alembic commands ###
