"""unique_payment_open_finance_id_per_user

Revision ID: b525108c8152
Revises: c3160de3ae62
Create Date: 2026-02-04 10:07:39.647610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b525108c8152'
down_revision: Union[str, Sequence[str], None] = 'c3160de3ae62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_open_finance_accounts_item_id'), table_name='open_finance_accounts')
    op.drop_index(op.f('ix_open_finance_accounts_pluggy_account_id'), table_name='open_finance_accounts')
    op.drop_table('open_finance_accounts')
    op.drop_index(op.f('ix_open_finance_items_pluggy_item_id'), table_name='open_finance_items')
    op.drop_index(op.f('ix_open_finance_items_user_id'), table_name='open_finance_items')
    op.drop_table('open_finance_items')
    op.drop_column('categories', 'type')
    op.drop_index(op.f('ix_payments_open_finance_id'), table_name='payments')
    op.create_index(op.f('ix_payments_open_finance_id'), 'payments', ['open_finance_id'], unique=False)
    op.create_unique_constraint('uq_payment_user_open_finance_id', 'payments', ['user_id', 'open_finance_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_user_open_finance_id', 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_open_finance_id'), table_name='payments')
    op.create_index(op.f('ix_payments_open_finance_id'), 'payments', ['open_finance_id'], unique=True)
    op.add_column('categories', sa.Column('type', sa.VARCHAR(), server_default=sa.text("'EXPENSE'::character varying"), autoincrement=False, nullable=False))
    op.create_table('open_finance_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pluggy_item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('UPDATED', 'UPDATING', 'LOGIN_ERROR', 'OUTDATED', 'WAITING_USER_INPUT', name='itemstatus'), autoincrement=False, nullable=False),
    sa.Column('bank_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name='open_finance_items_bank_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='open_finance_items_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='open_finance_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_open_finance_items_user_id'), 'open_finance_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_open_finance_items_pluggy_item_id'), 'open_finance_items', ['pluggy_item_id'], unique=True)
    op.create_table('open_finance_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pluggy_account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('CHECKING', 'SAVINGS', 'CREDIT', 'LOAN', 'INVESTMENT', 'OTHER', name='accounttype'), autoincrement=False, nullable=False),
    sa.Column('subtype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['open_finance_items.id'], name=op.f('open_finance_accounts_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('open_finance_accounts_pkey'))
    )
    op.create_index(op.f('ix_open_finance_accounts_pluggy_account_id'), 'open_finance_accounts', ['pluggy_account_id'], unique=True)
    op.create_index(op.f('ix_open_finance_accounts_item_id'), 'open_finance_accounts', ['item_id'], unique=False)
    # ### end Alembic commands ###
