"""add_category_and_merchant_flags

Revision ID: b879a29083f7
Revises: adfa8daea0fd
Create Date: 2026-02-16 13:26:22.889719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b879a29083f7"
down_revision: Union[str, Sequence[str], None] = "adfa8daea0fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column(
            "is_investment",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "categories",
        sa.Column(
            "ignored", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "merchant_aliases",
        sa.Column(
            "is_investment",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "merchant_aliases",
        sa.Column(
            "ignored", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchant_aliases", "ignored")
    op.drop_column("merchant_aliases", "is_investment")
    op.drop_column("categories", "ignored")
    op.drop_column("categories", "is_investment")
    # ### end Alembic commands ###
