"""add_alias_to_user_category_settings_v2

Revision ID: ba270fcb8375
Revises: c2ef90973c9b
Create Date: 2026-01-24 23:02:31.393138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ba270fcb8375"
down_revision: Union[str, Sequence[str], None] = "c2ef90973c9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_category_settings", sa.Column("alias", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_category_settings", "alias")
    # ### end Alembic commands ###
