"""add_pluggy_fields_to_categories_and_banks

Revision ID: be4eb94c823a
Revises: a47b99857605
Create Date: 2026-01-20 19:01:05.039581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be4eb94c823a'
down_revision: Union[str, Sequence[str], None] = 'a47b99857605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_open_finance_items_pluggy_item_id'), table_name='open_finance_items')
    op.drop_index(op.f('ix_open_finance_items_user_id'), table_name='open_finance_items')
    op.drop_table('open_finance_items')
    op.add_column('banks', sa.Column('ispb', sa.String(), nullable=True))
    op.add_column('banks', sa.Column('connector_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'banks', ['connector_id'])
    op.create_unique_constraint(None, 'banks', ['ispb'])
    op.add_column('categories', sa.Column('pluggy_id', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['pluggy_id'])
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'parent_id')
    op.drop_column('categories', 'pluggy_id')
    op.drop_constraint(None, 'banks', type_='unique')
    op.drop_constraint(None, 'banks', type_='unique')
    op.drop_column('banks', 'connector_id')
    op.drop_column('banks', 'ispb')
    op.create_table('open_finance_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pluggy_item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('UPDATED', 'UPDATING', 'LOGIN_ERROR', 'OUTDATED', 'WAITING_USER_INPUT', name='itemstatus'), autoincrement=False, nullable=False),
    sa.Column('bank_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('open_finance_items_bank_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('open_finance_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('open_finance_items_pkey'))
    )
    op.create_index(op.f('ix_open_finance_items_user_id'), 'open_finance_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_open_finance_items_pluggy_item_id'), 'open_finance_items', ['pluggy_item_id'], unique=True)
    # ### end Alembic commands ###
