"""make merchant_alias_id nullable

Revision ID: db5d99c51dde
Revises: ad7776d61e81
Create Date: 2026-02-20 12:24:01.085090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5d99c51dde'
down_revision: Union[str, Sequence[str], None] = 'ad7776d61e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'merchant_alias_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'merchant_alias_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
