"""add_neutral_category_type

Revision ID: e51894fb4870
Revises: 94a7b575b097
Create Date: 2026-01-13 13:04:06.462685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e51894fb4870"
down_revision: Union[str, Sequence[str], None] = "94a7b575b097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE categorytype ADD VALUE 'neutral'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
