"""Adicionando Merchants únicos por usuário alterando o nome do merchant alias de 'name' para 'pattern'

Revision ID: e6e441fd4e4a
Revises: 84c8510c110d
Create Date: 2026-01-02 19:24:17.957647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "e6e441fd4e4a"
down_revision: Union[str, Sequence[str], None] = "84c8510c110d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "banks",
        "logo_url",
        existing_type=sa.VARCHAR(),
        type_=sqlalchemy_utils.types.url.URLType(),
        existing_nullable=False,
    )
    # Rename 'name' to 'pattern' instead of dropping/adding
    op.alter_column("merchant_aliases", "name", new_column_name="pattern")

    # Add user_id as nullable to support existing data
    op.add_column("merchants", sa.Column("user_id", sa.UUID(), nullable=True))

    op.drop_constraint(op.f("merchants_name_key"), "merchants", type_="unique")
    op.create_unique_constraint(
        "uq_merchant_name_user_id", "merchants", ["name", "user_id"]
    )
    op.create_foreign_key(None, "merchants", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "merchants", type_="foreignkey")
    op.drop_constraint("uq_merchant_name_user_id", "merchants", type_="unique")
    op.create_unique_constraint(
        op.f("merchants_name_key"),
        "merchants",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("merchants", "user_id")

    # Rename 'pattern' back to 'name'
    op.alter_column("merchant_aliases", "pattern", new_column_name="name")

    op.alter_column(
        "banks",
        "logo_url",
        existing_type=sqlalchemy_utils.types.url.URLType(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
