"""remove_unique_constraint_category_name_slug

Revision ID: ecb426da0bc9
Revises: be4eb94c823a
Create Date: 2026-01-20 19:04:47.097554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb426da0bc9'
down_revision: Union[str, Sequence[str], None] = 'be4eb94c823a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
